name: Deploy to GitHub
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish-release-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joshlong/java-version-export-github-action@v28
        id: jve

      - name: Java without Cache
        uses: actions/setup-java@v4
        with:
            java-version: ${{ steps.jve.outputs.java_major_version }}
            distribution: 'temurin'

      - name: Build Metrics
        run: mvn -U -B clean package

      - name: Attach CLI to Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: cli/target/metrics-cli.jar
          fail_on_unmatched_files: true
